variables:
  SCHEDULER_PARAMETERS: '--nodes=1 --partition=power9 --export=NONE'
  GIT_SUBMODULE_STRATEGY: recursive

stages:
  - performance-regression

.gcc-mpi-cuda-performance-regression:
  variables: 
    CMAKE_CXX_COMPILER: $CI_PROJECT_DIR/external/Kokkos/bin/nvcc_wrapper
  script:
    - env -i bash --norc --noprofile ./scripts/darwin/build_fast.sh

  artifacts:
    expire_in: 3 days
    paths:
      - ${CI_PROJECT_DIR}/build/tst/regression/outputs/advection_performance/performance.png
      - ${CI_PROJECT_DIR}/build/tst/regression/outputs/advection_performance_mpi/performance.png

parthenon-power9-gcc-mpi-cuda-perf-manual:
  extends: .gcc-mpi-cuda-performance-regression
  stage: performance-regression
  when: manual
  except:
    - schedules

parthenon-power9-gcc-mpi-cuda-perf-schedule:
  extends: .gcc-mpi-cuda-performance-regression
  stage: performance-regression
  only:
    - schedules
    - develop

