variables:
  SCHEDULER_PARAMETERS: '--nodes=1 --partition=power9 --export=NONE'
  GIT_SUBMODULE_STRATEGY: recursive
  CMAKE_BUILD_TYPE: "Debug" 
  Kokkos_ARCH_POWER9: ON 
  Kokkos_ARCH_VOLTA70: ON 
  Kokkos_ENABLE_CUDA: ON 
  Kokkos_ENABLE_CUDA_UVM: OFF 
  Kokkos_ENABLE_CXX11: On 
  Kokkos_ENABLE_OPENMP: ON 
  PARTHENON_DISABLE_HDF5: ON 

stages:
  - performance-regression

# Is performed before the scripts in the stages step
before_script:
  - git clone https://github.com/lanl/parthenon-buildenv.git
  - env -i bash ./parthenon-buildenv/internal/scripts/setup.sh

parthenon-power9:
  stage: performance-regression
  script:
    - export CMAKE_CXX_COMPILER=$(pwd)/external/Kokkos/bin/nvcc_wrapper
    - >
      env -i bash ./parthenon-buildenv/internal/scripts/build.sh
      ${CMAKE_BUILD_TYPE}
      ${CMAKE_CXX_COMPILER}
      ${Kokkos_ARCH_POWER9}
      ${Kokkos_ARCH_VOLTA70}
      ${Kokkos_ENABLE_CUDA}
      ${Kokkos_ENABLE_CUDA_UVM}
      ${Kokkos_ENABLE_CXX11}
      ${Kokkos_ENABLE_OPENMP}
      ${PARTHENON_DISABLE_HDF5}


