variables:
  SCHEDULER_PARAMETERS: '--nodes=1 --partition=power9 --export=NONE'
  GIT_SUBMODULE_STRATEGY: recursive

stages:
  - performance-regression

# Is performed before the scripts in the stages step
before_script:
  - export HOME=${CI_PROJECT_DIR}
  - pwd
  - env
  - mkdir .ci-build
  - env -i bash setup.sh

parthenon-power9:
  stage: performance-regression
  script:
    - pwd
    - env -i bash build.sh
