
variables:
  SCHEDULER_PARAMETERS: "--nodes=1 --partition=power9"
  GIT_SUBMODULE_STRATEGY: recursive

stages:
  - unit

# Is performed before the scripts in the stages step
before_script:
  - export OMP_PROC_BIND=close
  - export OMP_PLACES=cores
  - export OMP_NUM_THREADS=1
  - export CMAKE_VERSION=3.10.3
  - export CTEST_OUTPUT_ON_FAILURE=1
  - export J=$(( $(nproc --all) / 4  + 1 )) && echo Using ${J} cores during build

parthenon-power9:
  stage: unit
  script:
    - echo "Beginning script"
    - mkdir build-cuda-debug
    - cd build-cuda-debug
    - cmake -DCMAKE_BUILD_TYPE=Debug -DHDF5_ROOT=/usr/local/hdf5/parallel
      -DKokkos_ENABLE_OPENMP=True -DKokkos_ARCH_WSM=True
      -DKokkos_ENABLE_CUDA=True -DKokkos_ARCH_PASCAL61=True
      -DMPIEXEC_PREFLAGS="--allow-run-as-root"
      -DCMAKE_CXX_COMPILER=${PWD}/../external/Kokkos/bin/nvcc_wrapper
      ../ && make -j${J} && ctest -j${J} -LE 'performance|regression'
    - cd ..
