variables:
  SCHEDULER_PARAMETERS: '--nodes=1 --partition=power9 --export=NONE'
  GIT_SUBMODULE_STRATEGY: recursive

stages:
  - performance-regression

# Is performed before the scripts in the stages step
before_script:
  - git clone https://github.com/lanl/parthenon-buildenv.git
  - env -i bash ./parthenon-buildenv/internal/scripts/setup.sh

parthenon-power9:
  stage: performance-regression
  script:
    - env -i bash ./parthenon-buildenv/internal/scripts/build.sh
