
language: cpp

compiler:
  - gcc-9.2.0

sudo: required

git:
  quiet: true

addons:
  apt:
    packages:
      - spack


before_install:
  - spack install cmake@3.15.3
  - spack install openmpi@4.0.2
  - spack install hdf5@1.10.6%openmpi@4.0.2

script:
  - mkdir build
  - cd build
  - cmake -DCMAKE_BUILD_TYPE=Debug ../ && make && make test
