comment:
  require_changes: true  # Only post a comment if coverage changes.
coverage:
  status:
    project:
      default:
        threshold: 1%
ignore:
  - "tst"
  - "cmake"
  - "external"
  - "scripts"
  - "docs"
