name: Check Formatting
on: push
jobs:
  check-formatting:
    name: Check Python/C++ Formatting
    runs-on: ubuntu-latest
    steps:
    - uses: AndrewGaspar/cpp-auto-formatter/check@v0.1
      with:
        clangFormatVersion: 8
        token: ${{ secrets.GITHUB_TOKEN }}
    - uses: psf/black@stable                                                                 
      with:
        options: "--check --verbose"
        src: "."
